/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    var numero = 25 
    val pi = 3.1416
    println("edad de $numero")
}
